# Changes here will be overwritten by Copier
_commit: 2026.7.4
_src_path: https://github.com/ninerealmlabs/precommit-template
ai: true
conventional_commits: true
docker: true
editorconfig: true
github_actions: true
markdown: true
markdown_render_check: false
python: true
shell: true
typos: true
web_format: true
web_format_tool: biome
yaml: true

