---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: forbid-yml
        name: Forbid .yml file extensions (use .yaml)
        entry: YAML file extensions must be .yaml
        stages: [pre-commit, manual]
        language: fail
        files: \.yml$
        exclude: |
          (?x)^(
            ^.*(copier-answers\.yml)$
          )$
      - id: forbid-rej
        name: Forbid .rej file extensions from `copier update`
        entry: Forbid .rej file extensions from `copier update`
        stages: [pre-commit, manual]
        language: fail
        files: \.rej$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500000]
        stages: [pre-commit, manual]
      - id: check-case-conflict
        stages: [pre-commit, manual]
      - id: check-merge-conflict
        stages: [pre-commit, manual]
      - id: check-yaml
        stages: [pre-commit, manual]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [pre-commit, manual]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: remove-crlf
        stages: [pre-commit, manual]
      - id: remove-tabs
        stages: [pre-commit, manual]
  - repo: https://github.com/sirosen/texthooks
    rev: "0.6.8"
    hooks:
      - id: fix-smartquotes
        stages: [pre-commit, manual]
      - id: fix-ligatures
        stages: [pre-commit, manual]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        args:
          - --write
          - --ignore-unknown
          - --no-error-on-unmatched-pattern
        stages: [pre-commit, manual]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.44.0"
    hooks:
      - id: markdownlint
        args: ["-f"]
        stages: [pre-commit, manual]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
        stages: [pre-commit, manual]
  # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  #   rev: 0.1.0
  #   hooks:
  #     - id: yamlfmt
  #       args: [--mapping, '2', --sequence, '4', --offset, '2', --preserve-quotes]
  #       stages: [pre-commit, ci]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.11.4"
    hooks:
      - id: ruff
        args: [--fix]
        stages: [pre-commit, manual]

  - repo: https://github.com/petalmd/dockerfile-pre-commit
    rev: v1.0
    hooks:
      - id: dockerlint
        stages: [pre-commit]
        # args: [--ignore, DL3025, --ignore, DL3018]

  ### NOTE: ".typos.toml" may be required to have _already been committed_
  ### in order for typos pre-commit hook to read it.
  ### In this case, comment out this block until ".typos.toml" has been committed successfully
  - repo: https://github.com/crate-ci/typos
    rev: v1.31.1
    hooks:
      - id: typos
        # args: []
        args: ["--config", ".typos.toml"]
        exclude: |
          (?x)^(
            ^.*(typos\.toml)$
          )$
        stages: [pre-commit, manual]
